Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
============== RESTART: C:\swetha_works\swetha_works\fileimg.py ==============
COMPUTER SCIENCE GROUP STUDENTS 
APPLICATION FOR ADMISSION-XI AND XII
APPLICATION NUMBER : 1
NAME: K.V.SWETHA
DATE OF BIRTH:23/03/2004
‘SCHOOL NAME PREVIOUSLY STUDIED : CHINMAYA VIDYALAYA
‘COURSE/GROUP: COMPUTER SCIENCE
PERCENTAGE OF MARKS IN 10: NINETY SIX PER CENT
AADHAR NUMBER :12345
MOTHER? NAME : K. VIJAYALAKSHMI
FATHER’S NAME : D. KALAISELVAN
MOTHER'S ANNUAL INCOME : TEN LAKHS
FATHER’S ANNUAL INCOME : FIFTEEN LAKHS
ADDRESS: SALMA SANJANA CASTLE CHOOLAIMEDU HG RD
CONTACT NUMBER :7890
COMMMUNITY: MBC


COMPUTER SCIENCE GROUP STUDENTS 
 
APPLICATION FOR ADMISSION-XI AND XI!
APPLICATION NUMBER : 2
NAME: K.KRISH
DATE OF BIRTH: 4/9/2004
‘7SCHOOL NAME PREVIOUSLY STUDIED: BHAVANS VIDYALAYA
‘COURSE/GROUP : COMPUTER SCIENCE
PERCENTAGE OF MARKS IN 10: NINETY EIGHT PER CENT
AADHAR NUMBER : 5678
MOTHER? NAME : K. VIJAYALAKSHMI
FATHER’S NAME : D. KALAISELVAN
MOTHER'S ANNUAL INCOME : TEN LAKHS
FATHER’S ANNUAL INCOME : FIFTEEN LAKHS.
ADDRESS: GREATA PAL KODAMBAKKAM
CONTACT NUMBER :998877
COMMMUNITY: BC


COMPUTER SCIENCE GROUP STUDENTS 
STUDENTS OF MBC COMMUNITY
APPLICATION FOR ADMISSION-XI AND XII
APPLICATION NUMBER : 1
NAME: K.V.SWETHA
DATE OF BIRTH:23/03/2004
‘SCHOOL NAME PREVIOUSLY STUDIED : CHINMAYA VIDYALAYA
‘COURSE/GROUP: COMPUTER SCIENCE
PERCENTAGE OF MARKS IN 10: NINETY SIX PER CENT
AADHAR NUMBER :12345
MOTHER? NAME : K. VIJAYALAKSHMI
FATHER’S NAME : D. KALAISELVAN
MOTHER'S ANNUAL INCOME : TEN LAKHS
FATHER’S ANNUAL INCOME : FIFTEEN LAKHS
ADDRESS: SALMA SANJANA CASTLE CHOOLAIMEDU HG RD
CONTACT NUMBER :7890
COMMMUNITY: MBC


STUDENTS OF MBC COMMUNITY
STUDENTS OF MBC COMMUNITY
STUDENTS OF BC COMMUNITY
STUDENTS OF BC COMMUNITY
 
APPLICATION FOR ADMISSION-XI AND XI!
APPLICATION NUMBER : 2
NAME: K.KRISH
DATE OF BIRTH: 4/9/2004
‘7SCHOOL NAME PREVIOUSLY STUDIED: BHAVANS VIDYALAYA
‘COURSE/GROUP : COMPUTER SCIENCE
PERCENTAGE OF MARKS IN 10: NINETY EIGHT PER CENT
AADHAR NUMBER : 5678
MOTHER? NAME : K. VIJAYALAKSHMI
FATHER’S NAME : D. KALAISELVAN
MOTHER'S ANNUAL INCOME : TEN LAKHS
FATHER’S ANNUAL INCOME : FIFTEEN LAKHS.
ADDRESS: GREATA PAL KODAMBAKKAM
CONTACT NUMBER :998877
COMMMUNITY: BC


STUDENTS OF BC COMMUNITY
>>> 
============== RESTART: C:\swetha_works\swetha_works\fileimg.py ==============
COMPUTER SCIENCE GROUP STUDENTS 
APPLICATION FOR ADMISSION-XI AND XII
APPLICATION NUMBER : 1
NAME: K.V.SWETHA
DATE OF BIRTH:23/03/2004
‘SCHOOL NAME PREVIOUSLY STUDIED : CHINMAYA VIDYALAYA
‘COURSE/GROUP: COMPUTER SCIENCE
PERCENTAGE OF MARKS IN 10: NINETY SIX PER CENT
AADHAR NUMBER :12345
MOTHER? NAME : K. VIJAYALAKSHMI
FATHER’S NAME : D. KALAISELVAN
MOTHER'S ANNUAL INCOME : TEN LAKHS
FATHER’S ANNUAL INCOME : FIFTEEN LAKHS
ADDRESS: SALMA SANJANA CASTLE CHOOLAIMEDU HG RD
CONTACT NUMBER :7890
COMMMUNITY: MBC


 
APPLICATION FOR ADMISSION-XI AND XI!
APPLICATION NUMBER : 2
NAME: K.KRISH
DATE OF BIRTH: 4/9/2004
‘7SCHOOL NAME PREVIOUSLY STUDIED: BHAVANS VIDYALAYA
‘COURSE/GROUP : COMPUTER SCIENCE
PERCENTAGE OF MARKS IN 10: NINETY EIGHT PER CENT
AADHAR NUMBER : 5678
MOTHER? NAME : K. VIJAYALAKSHMI
FATHER’S NAME : D. KALAISELVAN
MOTHER'S ANNUAL INCOME : TEN LAKHS
FATHER’S ANNUAL INCOME : FIFTEEN LAKHS.
ADDRESS: GREATA PAL KODAMBAKKAM
CONTACT NUMBER :998877
COMMMUNITY: BC


STUDENTS OF MBC COMMUNITY
APPLICATION FOR ADMISSION-XI AND XII
APPLICATION NUMBER : 1
NAME: K.V.SWETHA
DATE OF BIRTH:23/03/2004
‘SCHOOL NAME PREVIOUSLY STUDIED : CHINMAYA VIDYALAYA
‘COURSE/GROUP: COMPUTER SCIENCE
PERCENTAGE OF MARKS IN 10: NINETY SIX PER CENT
AADHAR NUMBER :12345
MOTHER? NAME : K. VIJAYALAKSHMI
FATHER’S NAME : D. KALAISELVAN
MOTHER'S ANNUAL INCOME : TEN LAKHS
FATHER’S ANNUAL INCOME : FIFTEEN LAKHS
ADDRESS: SALMA SANJANA CASTLE CHOOLAIMEDU HG RD
CONTACT NUMBER :7890
COMMMUNITY: MBC


STUDENTS OF BC COMMUNITY
 
APPLICATION FOR ADMISSION-XI AND XI!
APPLICATION NUMBER : 2
NAME: K.KRISH
DATE OF BIRTH: 4/9/2004
‘7SCHOOL NAME PREVIOUSLY STUDIED: BHAVANS VIDYALAYA
‘COURSE/GROUP : COMPUTER SCIENCE
PERCENTAGE OF MARKS IN 10: NINETY EIGHT PER CENT
AADHAR NUMBER : 5678
MOTHER? NAME : K. VIJAYALAKSHMI
FATHER’S NAME : D. KALAISELVAN
MOTHER'S ANNUAL INCOME : TEN LAKHS
FATHER’S ANNUAL INCOME : FIFTEEN LAKHS.
ADDRESS: GREATA PAL KODAMBAKKAM
CONTACT NUMBER :998877
COMMMUNITY: BC


>>> 
